"""Initial migration.

Revision ID: 65056f85c992
Revises: 
Create Date: 2023-08-06 21:57:30.875056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65056f85c992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ClassName', sa.String(length=20), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=True),
    sa.Column('PageName', sa.String(length=20), nullable=True),
    sa.Column('Remind', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ClassName')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('Subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Class_id', sa.Integer(), nullable=True),
    sa.Column('SubjectName', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Class_id'], ['Classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BaseWorks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Class_id', sa.Integer(), nullable=True),
    sa.Column('Subject_id', sa.Integer(), nullable=True),
    sa.Column('WorkOrExam', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Class_id'], ['Classes.id'], ),
    sa.ForeignKeyConstraint(['Subject_id'], ['Subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Class_id', sa.Integer(), nullable=True),
    sa.Column('Subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Class_id'], ['Classes.id'], ),
    sa.ForeignKeyConstraint(['Subject_id'], ['Subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Class_id', sa.Integer(), nullable=True),
    sa.Column('BaseWork_id', sa.Integer(), nullable=True),
    sa.Column('Range', sa.String(length=20), nullable=True),
    sa.Column('DueTime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['BaseWork_id'], ['BaseWorks.id'], ),
    sa.ForeignKeyConstraint(['Class_id'], ['Classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Works')
    op.drop_table('Schedule')
    op.drop_table('BaseWorks')
    op.drop_table('Subjects')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    op.drop_table('Classes')
    # ### end Alembic commands ###
