"""empty message

Revision ID: a66e5c1e70e4
Revises: 85c8058a5515
Create Date: 2023-08-28 14:52:15.015714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66e5c1e70e4'
down_revision = '85c8058a5515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BaseWorks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Suggest', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BaseWorks', schema=None) as batch_op:
        batch_op.drop_column('Suggest')

    # ### end Alembic commands ###
