"""empty message

Revision ID: c58e5c9833d8
Revises: d90fbf5d1d93
Create Date: 2023-08-09 16:29:51.583435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58e5c9833d8'
down_revision = 'd90fbf5d1d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Works', schema=None) as batch_op:
        batch_op.alter_column('DueTime',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Works', schema=None) as batch_op:
        batch_op.alter_column('DueTime',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
