"""empty message

Revision ID: d90fbf5d1d93
Revises: 0158fc51f56a
Create Date: 2023-08-09 12:02:56.423840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90fbf5d1d93'
down_revision = '0158fc51f56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BaseWorks', schema=None) as batch_op:
        batch_op.drop_column('WorkOrExam')

    with op.batch_alter_table('Works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('WorkOrExam', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Works', schema=None) as batch_op:
        batch_op.drop_column('WorkOrExam')

    with op.batch_alter_table('BaseWorks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('WorkOrExam', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
